### ISSUE TITLE
Pièces du jeu d'échecs

### ISSUE THREAD

**Issue by rchastain** [Loutcho/turbopascal#1]
Bonjour !

Un mot pour vous dire que votre échiquier est très joli. Les pièces sont vraiment très réussies. Je ne sais pas comment vous avez fait, mais chapeau !

En comparaison, les pièces de [Nero 5](https://github.com/rchastain/nero5) (dessinées également avec l'unité Graph) sont beaucoup moins réussies.

J'ai vu aussi votre programme en C qui fabrique des images SVG. Ce serait amusant d'employer cette technique avec vos pièces. Je ne sais pas si l'idée vous intéressera.

Je serais bien tenté de réutiliser votre échiquier, pour servir d'interface à un programme d'échecs qui n'en a pas. J'en ai toute une collection. :)

Cordialement.

Roland

![screenshot](https://user-images.githubusercontent.com/13957204/181713439-20a4ce94-daf5-442c-b475-70f12f348313.png)

**Comment by Loutcho** [comment]
Bonjour
Merci pour ces retours bien sympathiques. Sur du code datant d'il y a 26 ans et un dépôt figé me servant d'archive de disquettes, je ne m'y attendais pas du tout. A l'époque j'ai dû faire quelques esquisses papier à la règle et au compas avant report dans le code (grafisme.pas, procédures DessineXXX). Je vous en prie, sentez vous libre de réutiliser ou d'adapter ces recettes de cuisine, j'en serai très honoré. Oui l'idée de les retranscrire en SVG est pertinente.
Cordialement
LR.

**Comment by rchastain** [comment]
Merci pour la très aimable réponse. Voilà, j'ai mis le projet [là](https://gitlab.com/rchastain/ptcgraph-chessboard) pour me souvenir d'y travailler.

Si j'arrive à créer des images à partir des pièces, je le signalerai ici. J'ai déjà un peu regardé le code : ça devrait être assez facile. 

Bonne continuation !

**Comment by rchastain** [comment]
Bonjour ! Voici ce que ça donne pour le moment.

![Cavalier](https://github.com/Loutcho/turbopascal/assets/13957204/155dcd41-2d5e-4c2c-a16c-61f9a0faf9dd)
![Dame](https://github.com/Loutcho/turbopascal/assets/13957204/c9ef24f2-b2fb-4c94-a2f3-f92dbbc78c24)
![Fou](https://github.com/Loutcho/turbopascal/assets/13957204/76cb4fd5-7952-4175-871e-81957c0b46c2)
![Pion](https://github.com/Loutcho/turbopascal/assets/13957204/ad7bd0a0-1cc7-4008-8a6f-8483cf84f805)
![Roi](https://github.com/Loutcho/turbopascal/assets/13957204/493c00e4-d598-4db7-9e0a-dc412f80b1e5)
![Tour](https://github.com/Loutcho/turbopascal/assets/13957204/d2c99aa3-7eb3-480b-b7b0-b6d872cead5e)

Très content de ces petites pièces. :)

Cordialement.

Roland
